### PR TITLE
Devcontainer podman in rootless mode

### PR DESCRIPTION
**Pull request by brianegge**
https://code.visualstudio.com/remote/advancedcontainers/add-nonroot-user

### CODE REVIEW

**Comment by MatthewFlamm** [comment]
Thanks!  I tried running a codespaces instance from this PR and it starts in recovery mode while starting from the main branch starts fine.  Not sure what the issue is.

**Comment by brianegge** [comment]
Thanks for giving it a try. It works for me with rootless podman but I haven’t tested with docker. I was expecting it would work the same with docker. I’ll see if I can test it with docker. Are you running docker root full?

**Comment by MatthewFlamm** [comment]
I created a codespace in GitHub

**Comment by brianegge** [comment]
I made podman a separate configuration
image

**Review by MatthewFlamm — APPROVED** [review]
I can't test on podman but if it helps others contribute I'm +1

**Pull request merged**
