### PR TITLE
Fix for upstream 2024.1

### PR DESCRIPTION
**Pull request by dext0r**

### CODE REVIEW

**Comment by MatthewFlamm** [comment]
homeassistant just released a new tag in their repo, but it hasn't shown up in pypi yet.  It will have to be rerun once it shows up.

**Comment by MatthewFlamm** [comment]
#170 is maybe asking for this whole `testing_config` folder to be copied over, but this is good as a quick patch fix.

**Comment by dext0r** [comment]
> #170 is maybe asking for this whole `testing_config` folder to be copied over, but this is good as a quick patch fix.

I'm not sure that's a good idea. There are so many unnecessary files.

> homeassistant just released a new tag in their repo, but it hasn't shown up in pypi yet. It will have to be rerun once it shows up.

pypi has 2024.1.0b8 now, please rerun workflow

**Review by MatthewFlamm — APPROVED** [review]
Thanks!  LGTM

**Comment by MatthewFlamm** [comment]
Getting caught in a flurry of releases from home assistant that prevent publishing here.  Will keep trying.

**Pull request merged**
